#!/bin/bash
set -euo pipefail

# SkVM Environment Binding Script
# Auto-generated by compiler Pass 2

log() { echo "[env-bind] $*"; }
warn() { echo "[env-bind] WARNING: $*" >&2; }

# --- python runtime resolution ---------------------------------------------
# Prefer an already-active conda/venv. Otherwise use system python3/python.
# When no usable pip exists (module absent, or installs into the system
# interpreter are blocked, e.g. PEP 668), bootstrap a private venv at
# $SKVM_ENV_DIR (default: ./.skvm-env) and prepend its bin to PATH, so that
# processes started after this script inherit the bound environment.
PY=""

bootstrap_venv() {
  ENV_DIR="${SKVM_ENV_DIR:-$PWD/.skvm-env}"
  if [ ! -x "$ENV_DIR/bin/python" ]; then
    log "bootstrapping private venv at $ENV_DIR"
    "$PY" -m venv "$ENV_DIR" || { warn "venv creation failed"; return 1; }
  fi
  PATH="$ENV_DIR/bin:$PATH"
  export PATH
  PY="$ENV_DIR/bin/python"
  log "python: $PY"
}

ensure_python() {
  if [ -n "$PY" ]; then return 0; fi
  if [ -n "${CONDA_DEFAULT_ENV:-}" ] || [ -n "${VIRTUAL_ENV:-}" ]; then
    PY="$(command -v python || command -v python3)" || { warn "no python in active environment"; return 1; }
    return 0
  fi
  PY="$(command -v python3 || command -v python)" || { warn "no python interpreter found"; return 1; }
  if ! "$PY" -m pip --version >/dev/null 2>&1; then
    bootstrap_venv || return 1
  fi
}

pip_check() {
  ensure_python || return 1
  "$PY" -m pip show "$@"
}

pip_install() {
  ensure_python || return 1
  if "$PY" -m pip install "$@"; then return 0; fi
  # System-interpreter installs can be rejected (PEP 668 externally-managed,
  # or missing write permission) — retry once inside the private venv.
  case "$PY" in
    "${SKVM_ENV_DIR:-$PWD/.skvm-env}"/*) return 1 ;;
  esac
  warn "pip install failed on $PY; retrying inside a private venv"
  bootstrap_venv || return 1
  "$PY" -m pip install "$@"
}

install_system_pkg() {
  pkg="$1"

  if command -v brew >/dev/null 2>&1; then
    brew install "$pkg"
    return
  fi

  if command -v apt-get >/dev/null 2>&1; then
    apt-get install -y "$pkg"
    return
  fi

  if command -v dnf >/dev/null 2>&1; then
    dnf install -y "$pkg"
    return
  fi

  if command -v yum >/dev/null 2>&1; then
    yum install -y "$pkg"
    return
  fi

  if command -v winget >/dev/null 2>&1; then
    winget install --id "$pkg" -e
    return
  fi

  if command -v choco >/dev/null 2>&1; then
    choco install -y "$pkg"
    return
  fi

  warn "No supported system package manager found for $pkg"
  return 1
}

FAIL=0

# --- Dependency: <name> (<type>) ---
if <checkCommand> >/dev/null 2>&1; then
  log "<name>: present"
else
  log "<name>: missing, installing..."
  <installCommand> || { warn "Failed to install <name>"; FAIL=$((FAIL+1)); }
fi

# ... repeat for each dependency ...

if [ "$FAIL" -gt 0 ]; then
  warn "$FAIL dependencies failed to install"
  exit 1
fi

log "All dependencies satisfied"
